name: Jekyll site CI

on:
  push:
    branches: [ master ]

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Specify the target branch (optional)
    - uses: helaili/jekyll-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target_branch: 'gh-pages'
        
    - uses: actions/checkout@master
    - name: copy
    	run: |
        files=$(find _refs/_* -type f) # get the file list
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git fetch                         # fetch branches
        git checkout gh-pages       # checkout to your branch
        git checkout ${GITHUB_REF##*/} -- $files # copy files from the source branch
        git add -A
        git mv $files refs/
        git diff-index --quiet HEAD ||  git commit -am "deploy files"  # commit to the repository (ignore if no modification)
        git push origin gh-pages # push to remote branch
         
